name: Scrape

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SECRETS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo 'JSON_KEY="${{ secrets.JSON_KEY }}"' > scraping/.env
          echo 'BIN_ID="${{ secrets.BIN_ID }}"' >> scraping/.env

      - name: Debugging - Show .env
        run: cat scraping/.env

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "node16"

      - name: Install dependencies
        run: cd scraping && npm ci

      - name: Run script
        run: cd scraping && node index.js
