name: Run Node.js Script

on:
  schedule:
    - cron: "54 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SECRETS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "${{ secrets.ENV_FILE }}" > scraping/.env

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd scraping && npm ci

      - name: Run script
        run: cd scraping && node index.js
